name: Create Docker Container

on: [push]

jobs:
  mlops-container:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build container
        run: |
          docker network create data
          docker build --tag inference:latest .
          docker run -d -p 8000:8000 --network data --name inference_container inference:latest
      - name: Install linters
        run: |
          pip install flake8 black isort
      - name: Run flake8
        run: |
         flake8 ${{ inputs.service-dir}}
      - name: Run black
        run: |
          black ${{ inputs.service-dir }}
      - name: Run isort
        run: |
          isort ${{ inputs.service-dir }}